USE master;
GO

-- 21126090 - 21126054 - 21126072 - 21126088

-- MỤC LỤC

-- 1. TẠO CƠ SỞ DỮ LIỆU
-- 2. PHÂN QUYỀN
-- 3. TRIGGER
-- 4. NHẬP LIỆU


-- 1. TẠO CƠ SỞ DỮ LIỆU----------------------------------------------------------------------------------------------------
--USE MASTER 
--GO
--DROP DATABASE PKNHAKHOA
IF NOT EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = 'PKNHAKHOA')
BEGIN
    CREATE DATABASE PKNHAKHOA;
END
GO

USE PKNHAKHOA;
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KHACHHANG')
BEGIN
    CREATE TABLE KHACHHANG 
    (
        SODT VARCHAR(10) PRIMARY KEY CHECK (LEN(SODT) = 10),
        HOTEN NVARCHAR(50),
        PHAI NVARCHAR(5) CHECK(PHAI IN (N'Nam', N'Nữ')),
        NGAYSINH DATE,
        DIACHI NVARCHAR(250),
        MATKHAU VARCHAR(20),
        _DAKHOA BIT DEFAULT 0
    );
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'NHASI')
BEGIN
	CREATE TABLE NHASI 
	(
		MANS VARCHAR(10) PRIMARY KEY,
		HOTEN NVARCHAR(50),
		PHAI NVARCHAR(5) CHECK(PHAI IN (N'Nam', N'Nữ')),
		GIOITHIEU NVARCHAR(500),
		MATKHAU VARCHAR(20),
		_DAKHOA BIT DEFAULT 0
	);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'NHANVIEN')
BEGIN
	CREATE TABLE NHANVIEN 
	(
		MANV VARCHAR(10) PRIMARY KEY,
		HOTEN NVARCHAR(50),
		PHAI NVARCHAR(5) CHECK(PHAI IN (N'Nam', N'Nữ')),
		VITRICV NVARCHAR(50),
		MATKHAU VARCHAR(20),
		_DAKHOA BIT DEFAULT 0
	);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'QTV')
BEGIN
	CREATE TABLE QTV 
	(
		MAQTV VARCHAR(10) PRIMARY KEY,
		HOTEN NVARCHAR(50),
		PHAI NVARCHAR(5) CHECK(PHAI IN (N'Nam', N'Nữ')),
		MATKHAU VARCHAR(20),
	);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LOAITHUOC')
BEGIN
	CREATE TABLE LOAITHUOC
	(
		MATHUOC VARCHAR(10) PRIMARY KEY,
		TENTHUOC NVARCHAR(50),
		DONVITINH NVARCHAR(20),
		CHIDINH NVARCHAR(200),
		SLTON INT CHECK (SLTON >= 0),
		SLNHAP INT CHECK (SLNHAP > 0),
		SLDAHUY INT CHECK (SLDAHUY >= 0),
		NGAYHETHAN DATE,
		DONGIA FLOAT CHECK (DONGIA > 0)
	);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LOAIDICHVU')
BEGIN
	CREATE TABLE LOAIDICHVU
	(
		MADV VARCHAR(10) PRIMARY KEY,
		TENDV NVARCHAR(50),
		MOTA NVARCHAR(500),
		DONGIA FLOAT CHECK (DONGIA > 0)
	);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CA')
BEGIN
	CREATE TABLE CA
	(
		MACA VARCHAR(10) PRIMARY KEY,
		GIOBATDAU TIME,
		GIOKETTHUC TIME
	);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CHITIETDV')
BEGIN
	CREATE TABLE CHITIETDV
	(
		MADV VARCHAR(10),
		SOTT INT,
		SODT VARCHAR(10),
		SOLUONG INT CHECK(SOLUONG > 0),
		DONGIALUCTHEM FLOAT CHECK(DONGIALUCTHEM > 0),
		PRIMARY KEY(SODT, SOTT, MADV)
	);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CHITIETTHUOC')
BEGIN
	CREATE TABLE CHITIETTHUOC
	(
		MATHUOC VARCHAR(10),
		SOTT INT,
		SODT VARCHAR(10),
		SOLUONG INT CHECK (SOLUONG > 0),
		THOIDIEMDUNG NVARCHAR(200),
		DONGIALUCTHEM FLOAT CHECK(DONGIALUCTHEM > 0),
		PRIMARY KEY(SODT, SOTT, MATHUOC)
	);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LICHRANH')
BEGIN
	CREATE TABLE LICHRANH
	(
		MANS VARCHAR(10),
		SOTT INT,
		MACA VARCHAR(10),
		NGAY DATE,
		PRIMARY KEY(MANS, SOTT)
	);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LICHHEN')
BEGIN
	CREATE TABLE LICHHEN
	(
		MANS VARCHAR(10),
		SOTT INT,
		LYDOKHAM NVARCHAR(200),
		SODT VARCHAR(10)
		PRIMARY KEY(MANS, SOTT, SODT)
	);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'HOSOBENH')
BEGIN
	CREATE TABLE HOSOBENH
	(
		SODT VARCHAR(10),
		SOTT INT,
		NGAYKHAM DATE,
		DANDO NVARCHAR(500),
		MANS VARCHAR(10),
		_DAXUATHOADON BIT DEFAULT 0
		PRIMARY KEY(SODT, SOTT)
	);
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'HOADON')
BEGIN
	CREATE TABLE HOADON
	(
		SODT VARCHAR(10),
		SOTT INT,
		NGAYXUAT DATE,
		TONGCHIPHI FLOAT CHECK (TONGCHIPHI > 0),
		_DATHANHTOAN BIT DEFAULT 0,
		MANV VARCHAR(10)
		PRIMARY KEY(SODT, SOTT)
	);
END

--PK1 LICHRANH(MANS) --> NHASI(MANS)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_LR_NS')
BEGIN
    ALTER TABLE LICHRANH
    ADD CONSTRAINT FK_LR_NS
    FOREIGN KEY(MANS)
    REFERENCES NHASI(MANS);
END

--PK2 LICHRANH(MACA) --> CA(MACA)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_LR_CA')
BEGIN
    ALTER TABLE LICHRANH
    ADD CONSTRAINT FK_LR_CA
    FOREIGN KEY(MACA)
    REFERENCES CA(MACA);
END

--PK3 LICHHEN(MANS, SOTT) --> LICHRANH(MANS, SOTT)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_LH_LR')
BEGIN
    ALTER TABLE LICHHEN
    ADD CONSTRAINT FK_LH_LR
    FOREIGN KEY(MANS, SOTT)
    REFERENCES LICHRANH(MANS, SOTT);
END

--PK4 LICHHEN(SODT) --> KHACHHANG(SODT)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_LH_KH')
BEGIN
	ALTER TABLE LICHHEN
	ADD CONSTRAINT FK_LH_KH
	FOREIGN KEY(SODT)
	REFERENCES KHACHHANG(SODT);
END

-- PK5 HOSOBENH(MANS) --> NHASI(MANS)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_HSB_NS')
BEGIN
    ALTER TABLE HOSOBENH
    ADD CONSTRAINT FK_HSB_NS
    FOREIGN KEY(MANS)
    REFERENCES NHASI(MANS);
END

-- PK6 HOSOBENH(SODT) --> KHACHHANG(SODT)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_HSB_KH')
BEGIN
    ALTER TABLE HOSOBENH
    ADD CONSTRAINT FK_HSB_KH
    FOREIGN KEY(SODT)
    REFERENCES KHACHHANG(SODT);
END

-- PK7 HOADON(SODT, SOTT) --> HOSOBENH(SODT, SOTT)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_HD_HSB')
BEGIN
    ALTER TABLE HOADON
    ADD CONSTRAINT FK_HD_HSB
    FOREIGN KEY(SODT, SOTT)
    REFERENCES HOSOBENH(SODT, SOTT);
END

-- PK8 HOADON(MANV) --> NHANVIEN(MANV)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_HD_NV')
BEGIN
    ALTER TABLE HOADON
    ADD CONSTRAINT FK_HD_NV
    FOREIGN KEY(MANV)
    REFERENCES NHANVIEN(MANV);
END

-- PK9 CHITIETDV(MADV) --> LOAIDICHVU(MADV)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_CTDV_LDV')
BEGIN
    ALTER TABLE CHITIETDV
    ADD CONSTRAINT FK_CTDV_LDV
    FOREIGN KEY(MADV)
    REFERENCES LOAIDICHVU(MADV);
END

-- PK10 CHITIETDV(SODT, SOTT) --> HOSOBENH(SODT, SOTT)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_CTDV_HSB')
BEGIN
    ALTER TABLE CHITIETDV
    ADD CONSTRAINT FK_CTDV_HSB
    FOREIGN KEY(SODT, SOTT)
    REFERENCES HOSOBENH(SODT, SOTT);
END

-- PK11 CHITIETTHUOC(MATHUOC) --> LOAITHUOC(MATHUOC)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_CTT_LT')
BEGIN
    ALTER TABLE CHITIETTHUOC
    ADD CONSTRAINT FK_CTT_LT
    FOREIGN KEY(MATHUOC)
    REFERENCES LOAITHUOC(MATHUOC);
END

-- PK12 CHITIETTHUOC(SODT, SOTT) --> HOSOBENH(SODT, SOTT)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_CTT_HSB')
BEGIN
    ALTER TABLE CHITIETTHUOC
    ADD CONSTRAINT FK_CTT_HSB
    FOREIGN KEY(SODT, SOTT)
    REFERENCES HOSOBENH(SODT, SOTT);
END
-----------------------------------------------------------------------------------------------------------------

-- 2. PHÂN QUYỀN-------------------------------------------------------------------------------------------------
USE master;
GO

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'loginKH')
BEGIN
    CREATE LOGIN loginKH WITH PASSWORD = 'password123@';
END

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'loginNS')
BEGIN
    CREATE LOGIN loginNS WITH PASSWORD = 'password123@';
END

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'loginNV')
BEGIN
    CREATE LOGIN loginNV WITH PASSWORD = 'password123@';
END

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'loginQTV')
BEGIN
    CREATE LOGIN loginQTV WITH PASSWORD = 'password123@';
END

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'loginServer')
BEGIN
    CREATE LOGIN loginServer WITH PASSWORD = 'password123@';
END
