version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 12345
      MSSQL_PID: Developer
      MSSQL_DATABASE: dentist