version: "3.8"

services:
  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    environment:
      SA_PASSWORD: password123@
      ACCEPT_EULA: Y
      MSSQL_PID: "Developer"
      MSSQL_CONFIG_CONNECTIVITY: "LOCAL"  
    ports:
      - "1444:1433"
    # volumes:
    #  - sqlserver_volume:/var/opt/mssql
    networks:
      my_network:
         ipv4_address: 10.0.5.2 # Đặt địa chỉ IP tĩnh cho container
# volumes:
#   sqlserver_volume:
#     driver: local
networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet:  10.0.5.2/30 # Đặt subnet cho mạng cầu
          gateway: 10.0.5.3 # Đặt gateway cho mạng cầu

# docker compose -f mssql.yml up -d
