version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    environment:
      SA_PASSWORD: password123@
      ACCEPT_EULA: Y
      MSSQL_PID: "Developer"
      MSSQL_CONFIG_CONNECTIVITY: "LOCAL"
    ports:
      - "1444:1433"

networks:
  my_network:
    driver: bridge

