services: 
  mysql:
    image: mysql:5.7.40 
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dentists
      MYSQL_USER: test
      MYSQL_PASSWORD: test
   networks:
      mynetwork:
        ipv4_address:  172.17.0.1

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet:  172.17.0.1/16

