version: '3.8'
services: 
  mysql:
    image: mysql:5.7.40 
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dentists
      MYSQL_USER: test
      MYSQL_PASSWORD: test