

CREATE TABLE KHACHHANG 
(
    SODT VARCHAR(11) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    PHAI NVARCHAR(5) CHECK(PHAI IN (N'Nam', N'Nữ')),
    NGAYSINH DATE,
	DIACHI NVARCHAR(250),
	MATKHAU VARCHAR(20),
	_DAKHOA BIT
);

CREATE TABLE NHASI 
(
    MANS VARCHAR(10) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    PHAI NVARCHAR(5) CHECK(PHAI IN (N'Nam', N'Nữ')),
    GIOITHIEU NVARCHAR(500),
	MATKHAU VARCHAR(20),
	_DAKHOA BIT
);

INSERT INTO NHASI VALUES ('NS0001', N'Nguyễn Văn A', N'Nam', N'Nhà sĩ chuyên khoa nha', '123456', 0);
CREATE TABLE NHANVIEN 
(
    MANV VARCHAR(10) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    PHAI NVARCHAR(5) CHECK(PHAI IN (N'Nam', N'Nữ')),
    VITRICV NVARCHAR(50),
	MATKHAU VARCHAR(20),
	_DAKHOA BIT
);

CREATE TABLE QTV 
(
    MAQTV VARCHAR(10) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    PHAI NVARCHAR(5) CHECK(PHAI IN (N'Nam', N'Nữ')),
	MATKHAU VARCHAR(20)
);

CREATE TABLE LOAITHUOC
(
	MATHUOC VARCHAR(10) PRIMARY KEY,
    TENTHUOC NVARCHAR(50),
    DONVITINH NVARCHAR(20),
	CHIDINH NVARCHAR(200),
	SOLUONG INT,
	NGAYHETHAN DATE,
	DONGIA FLOAT
);

CREATE TABLE LOAIDICHVU
(
	MADV VARCHAR(10) PRIMARY KEY,
    TENDV NVARCHAR(50),
    MOTA NVARCHAR(500),
	DONGIA FLOAT
);

CREATE TABLE CHITIETDV
(
	MADV VARCHAR(10),
	STT INT,
	SODT VARCHAR(11),
	SOLUONG INT,
    PRIMARY KEY(SODT, STT, MADV)
);

CREATE TABLE CHITIETTHUOC
(
	MATHUOC VARCHAR(10),
	STT INT,
	SODT VARCHAR(11),
	SOLUONG INT,
	THOIDIEMDUNG NVARCHAR(200),
    PRIMARY KEY(SODT, STT, MATHUOC)
);

CREATE TABLE LICHRANH
(
	MANS VARCHAR(10),
	STT INT,
	GIOBATDAU DATE,
	GIOKETTHUC DATE,
	_DACOHEN BIT,
    PRIMARY KEY(MANS, STT)
);

CREATE TABLE LICHHEN
(
	MASOHEN VARCHAR(10) PRIMARY KEY,
	NGAYGIOKHAM DATE,
	LYDOKHAM NVARCHAR(200),
	MANS VARCHAR(10),
	SODT VARCHAR(11)
);

CREATE TABLE HOSOBENH
(
	SODT VARCHAR(11),
	STT INT,
	NGAYKHAM DATE,
	DANDO NVARCHAR(200),
	MANS VARCHAR(10),
	_DAXUATHOADON BIT,
	PRIMARY KEY(SODT, STT)
);

CREATE TABLE HOADON
(
	SODT VARCHAR(11),
	STT INT,
	NGAYXUAT DATE,
	TONGCHIPHI FLOAT,
	_DATHANHTOAN BIT,
	MANV VARCHAR(10),
	PRIMARY KEY(SODT, STT)
);

--PK1 LICHRANH(MANS) --> NHASI(MANS)
ALTER TABLE LICHRANH
ADD CONSTRAINT FK_LR_NS
FOREIGN KEY(MANS)
REFERENCES NHASI(MANS);

--PK2 LICHHEN(MANS) --> NHASI(MANS)
ALTER TABLE LICHHEN
ADD CONSTRAINT FK_LH_NS
FOREIGN KEY(MANS)
REFERENCES NHASI(MANS);

--PK3 LICHHEN(SODT) --> KHACHHANG(SODT)
ALTER TABLE LICHHEN
ADD CONSTRAINT FK_LH_KH
FOREIGN KEY(SODT)
REFERENCES KHACHHANG(SODT);

--PK4 HOSOBENH(MANS) --> NHASI(MANS)
ALTER TABLE HOSOBENH
ADD CONSTRAINT FK_HSB_NS
FOREIGN KEY(MANS)
REFERENCES NHASI(MANS);

--PK5 HOSOBENH(SODT) --> KHACHHANG(SODT)
ALTER TABLE HOSOBENH
ADD CONSTRAINT FK_HSB_KH
FOREIGN KEY(SODT)
REFERENCES KHACHHANG(SODT);

--PK6 HOADON(SODT, STT) --> HOSOBENH(SODT, STT)
ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_HSB
FOREIGN KEY(SODT, STT)
REFERENCES HOSOBENH(SODT, STT);

--PK7 HOADON(MANV) --> NHANVIEN(MANV)
ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_NV
FOREIGN KEY(MANV)
REFERENCES NHANVIEN(MANV);

--PK8 CHITIETDV(MADV) --> LOAIDICHVU(MADV)
ALTER TABLE CHITIETDV
ADD CONSTRAINT FK_CTDV_LDV
FOREIGN KEY(MADV)
REFERENCES LOAIDICHVU(MADV);

--PK9 CHITIETDV(SODT, STT) --> HOSOBENH(SODT, STT)
ALTER TABLE CHITIETDV
ADD CONSTRAINT FK_CTDV_HSB
FOREIGN KEY(SODT, STT)
REFERENCES HOSOBENH(SODT, STT);

--PK10 CHITIETTHUOC(MATHUOC) --> LOAITHUOC(MATHUOC)
ALTER TABLE CHITIETTHUOC
ADD CONSTRAINT FK_CTT_LT
FOREIGN KEY(MATHUOC)
REFERENCES LOAITHUOC(MATHUOC);

--PK11 CHITIETTHUOC(SODT, STT) --> HOSOBENH(SODT, STT)
ALTER TABLE CHITIETTHUOC
ADD CONSTRAINT FK_CTT_HSB
FOREIGN KEY(SODT, STT)
REFERENCES HOSOBENH(SODT, STT);