CREATE OR ALTER PROC SP_GETLICHRANHNS_NV AS BEGIN 
	BEGIN TRAN BEGIN TRY -- LICH CO HEN CUA NHA SI
	SELECT
	    NGAY,
	    CA.MACA,
	    GIOBATDAU,
	    GIOKETTHUC,
	    LH.SOTT SOTTLH,
	    LH.MANS,
	    NS.HOTEN HOTENNS,
	    KH.SODT SODTKH,
	    KH.HOTEN HOTENKH,
	    LH.LYDOKHAM LYDOKHAM
	FROM LICHHEN LH
	    JOIN NHASI NS ON NS.MANS = LH.MANS
	    JOIN LICHRANH LR2 ON LR2.MANS = LH.MANS AND LH.SOTT = LR2.SOTT
	    JOIN CA ON CA.MACA = LR2.MACA
	    JOIN KHACHHANG KH ON KH.SODT = LH.SODT
	WHERE
	    DATEDIFF(DAY, GETDATE(), NGAY) <= 7
	ORDER BY NGAY
	-- LICH CHUA CO HEN CUA NHA SI
	SELECT
	    NGAY,
	    CA.MACA,
	    GIOBATDAU,
	    GIOKETTHUC,
	    LR.SOTT SOTTLR,
	    LR.MANS,
	    HOTEN HOTENNS
	FROM LICHRANH LR
	    JOIN CA ON CA.MACA = LR.MACA
	    JOIN NHASI NS ON NS.MANS = LR.MANS
	WHERE NOT EXISTS (
	        SELECT 1
	        FROM LICHHEN LH
	        WHERE
	            LH.MANS = LR.MANS
	            AND LH.SOTT = LR.SOTT
	    )
	    AND DATEDIFF(DAY, GETDATE(), NGAY) <= 7
	ORDER BY
	    NGAY
	END TRY BEGIN CATCH
	ROLLBACK TRAN;
	DECLARE @errorMessage NVARCHAR(200) = ERROR_MESSAGE();
	THROW 51000, @errorMessage, 1;
	RETURN END CATCH COMMIT TRAN 
