-----------------------------------------------------------------------------------------------------------------

-- 2. PHÂN QUYỀN-------------------------------------------------------------------------------------------------
USE master;
GO

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'loginKH')
BEGIN
    CREATE LOGIN loginKH WITH PASSWORD = 'password123@';
END

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'loginKHOnline')
BEGIN
    CREATE LOGIN loginKHOnline WITH PASSWORD = 'password123@';
END

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'loginNS')
BEGIN
    CREATE LOGIN loginNS WITH PASSWORD = 'password123@';
END

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'loginNV')
BEGIN
    CREATE LOGIN loginNV WITH PASSWORD = 'password123@';
END

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'loginQTV')
BEGIN
    CREATE LOGIN loginQTV WITH PASSWORD = 'password123@';
END

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'loginServer')
BEGIN
    CREATE LOGIN loginServer WITH PASSWORD = 'password123@';
END


USE PKNHAKHOA;
GO

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'userKH')
BEGIN
    CREATE USER userKH FOR LOGIN loginKH;
END

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'userKHOnline')
BEGIN
    CREATE USER userKHOnline FOR LOGIN loginKHOnline;
END

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'userNS')
BEGIN
    CREATE USER userNS FOR LOGIN loginNS;
END

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'userNV')
BEGIN
    CREATE USER userNV FOR LOGIN loginNV;
END

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'userQTV')
BEGIN
    CREATE USER userQTV FOR LOGIN loginQTV;
END

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'userServer')
BEGIN
    CREATE USER userServer FOR LOGIN loginServer;
END

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'QTV')
BEGIN
    EXEC SP_ADDROLE 'QTV';
END

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'KHACHHANG')
BEGIN
    EXEC SP_ADDROLE 'KHACHHANG';
END

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'KHACHHANGONLINE')
BEGIN
    EXEC SP_ADDROLE 'KHACHHANGONLINE';
END

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'NHANVIEN')
BEGIN
    EXEC SP_ADDROLE 'NHANVIEN';
END

IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = 'NHASI')
BEGIN
    EXEC SP_ADDROLE 'NHASI';
END

EXEC sp_addrolemember 'QTV', 'userQTV'
EXEC sp_addrolemember 'KHACHHANG', 'userKH'
EXEC sp_addrolemember 'KHACHHANGONLINE', 'userKHOnline'
EXEC sp_addrolemember 'NHANVIEN', 'userNV'
EXEC sp_addrolemember 'NHASI', 'userNS'
EXEC sp_addrolemember db_datareader, 'userServer'

USE PKNHAKHOA
GO

--I/ Phân quyền cho role NHANVIEN

--1/ XEM LỊCH TRỰC TỪ NGÀY HIỆN TẠI ĐẾN 7 NGÀY KẾ
GRANT EXECUTE ON SP_GETLICHRANHNS_NV TO NHANVIEN;

--2/ TẠO TÀI KHOẢN KHÁCH HÀNG
GRANT EXECUTE ON SP_TAOTKKH_NV TO NHANVIEN;

--3/ TẠO HÓA ĐƠN
GRANT EXECUTE ON SP_TAOHOADON_NV TO NHANVIEN;

--4/ XÁC NHẬN THANH TOÁN HÓA ĐƠN
GRANT EXECUTE ON SP_THANHTOANHOADON_NV TO NHANVIEN;

--5/ TRUY VẤN HÓA ĐƠN
GRANT EXECUTE ON SP_GETHOADON1KH_NV TO NHANVIEN;

--6/ ĐỔI MẬT KHẨU
GRANT EXECUTE ON SP_DOIMK_NV TO NHANVIEN;

--7/ XEM DANH MỤC THUỐC
GRANT EXECUTE ON SP_GETALLTHUOC_NV_QTV_NS TO NHANVIEN;

--8/ XEM DANH MỤC DỊCH VỤ
GRANT EXECUTE ON SP_XEMDANHSACHDICHVU_ALL TO NHANVIEN;

--9/ TRUY VẤN HỒ SƠ KHÁM BỆNH
GRANT EXECUTE ON SP_GETHSB1KH_NV_NS_KH TO NHANVIEN;

--10/ TẠO LỊCH HẸN
GRANT EXECUTE ON SP_DATLICHHEN_NV_KH TO NHANVIEN;

--11/ HỦY LỊCH HẸN
GRANT EXECUTE ON SP_DELETELICHHEN_NV_KH TO NHANVIEN;

--12/ XEM DANH SÁCH TẤT CẢ NHA SĨ CHƯA BỊ KHÓA TÀI KHOẢN
GRANT EXECUTE ON SP_XEMDANHSACHNHASI_ALL TO NHANVIEN;

--13/ XEM THÔNG TIN TOÀN BỘ BẢNG CA
GRANT EXECUTE ON SP_XEMCA_ALL TO NHANVIEN;

--II/ Phân quyền cho role NHASI
--1/ XEM CÁC CA ĐỦ 2 NG TRỰC TRỪ CA MÌNH ĐÃ ĐẶT (TỪ NGÀY HIỆN TẠI ĐẾN 30 NGÀY SAU)
GRANT EXECUTE ON SP_XEMCADU2NGTRUC_NS TO NHASI;

--2/ TRUY VẤN CÁC LỊCH HẸN CỦA MÌNH (TỪ NGÀY HIỆN TẠI ĐẾN 30 NGÀY SAU)
GRANT EXECUTE ON SP_XEMLICHHENNS_NS TO NHASI;

--3/ TRUY VẤN CÁC LỊCH RẢNH CỦA MÌNH MÀ CHƯA ĐƯỢC ĐẶT LỊCH (TỪ NGÀY HIỆN TẠI ĐẾN 30 NGÀY SAU)
GRANT EXECUTE ON SP_LICHRANHCHUADUOCDAT_NS TO NHASI;

--4/ ĐĂNG KÝ LỊCH RẢNH
GRANT EXECUTE ON SP_DANGKYLR_NS TO NHASI;

--5/ HỦY LỊCH RẢNH
GRANT EXECUTE ON SP_HUYLR_NS TO NHASI;

--6/ TẠO BỆNH ÁN MỚI
GRANT EXECUTE ON SP_TAOBENHAN_NS TO NHASI;

--7/ THÊM CTDV VÀO BỆNH ÁN
GRANT EXECUTE ON SP_THEMCTDV_NS TO NHASI;

--8/ THÊM CT THUỐC VÀO BỆNH ÁN
GRANT EXECUTE ON SP_THEMCTTHUOC_NS TO NHASI;

--9/ ĐỔI MẬT KHẨU
GRANT EXECUTE ON SP_DOIMK_NS TO NHASI;

--10/ XEM DANH MỤC THUỐC
GRANT EXECUTE ON SP_GETALLTHUOC_NV_QTV_NS TO NHASI;

--11/ XEM DANH MỤC DỊCH VỤ
GRANT EXECUTE ON SP_GETALLTHUOC_NV_QTV_NS TO NHASI;

--12/ TRUY VẤN HỒ SƠ KHÁM BỆNH
GRANT EXECUTE ON SP_GETHSB1KH_NV_NS_KH TO NHASI;

--13/ XEM DANH SÁCH TẤT CẢ NHA SĨ CHƯA BỊ KHÓA TÀI KHOẢN
GRANT EXECUTE ON SP_XEMDANHSACHNHASI_ALL TO NHASI;

--14/ XEM THÔNG TIN TOÀN BỘ BẢNG CA
GRANT EXECUTE ON SP_XEMCA_ALL TO NHASI;

--15/ XEM DANH MỤC DỊCH VỤ
GRANT EXECUTE ON SP_XEMDANHSACHDICHVU_ALL TO NHASI;

--III/ Phân quyền cho role KHACHHANG
--1/ TẠO TÀI KHOẢN
GRANT EXECUTE ON SP_TAOTKKH_KH TO KHACHHANG;

--2/ XEM THÔNG TIN CÁ NHÂN CỦA KH
GRANT EXECUTE ON SP_XEMTHONGTIN_KH TO KHACHHANG;

--3/ CẬP NHẬT THÔNG TIN CÁ NHÂN KH
GRANT EXECUTE ON SP_CAPNHATTHONGTIN_KH TO KHACHHANG;

--4/ XEM LỊCH RẢNH CỦA TẤT CẢ NHA SĨ TỪ HIỆN TẠI ĐẾN 30 NGÀY SAU
GRANT EXECUTE ON SP_LRCHUADATTATCANS_KH TO KHACHHANG;

--5/ TRUY VẤN LOẠI THUỐC
GRANT EXECUTE ON SP_TRUYVANLOAITHUOC_KH TO KHACHHANG;

--6/ TRUY VẤN LOẠI DỊCH VỤ
GRANT EXECUTE ON SP_TRUYDICHVU_KH TO KHACHHANG;

--7/ TRUY VẤN LỊCH HẸN
GRANT EXECUTE ON SP_TRUYVANLICHHEN_KH TO KHACHHANG;

--8/ XEM DANH MỤC DỊCH VỤ
GRANT EXECUTE ON SP_XEMDANHSACHDICHVU_ALL TO KHACHHANG;

--9/ TRUY VẤN HỒ SƠ KHÁM BỆNH
GRANT EXECUTE ON SP_GETHSB1KH_NV_NS_KH TO KHACHHANG;

--10/ TẠO LỊCH HẸN
GRANT EXECUTE ON SP_DATLICHHEN_NV_KH TO KHACHHANG;

--11/ HỦY LỊCH HẸN
GRANT EXECUTE ON SP_DELETELICHHEN_NV_KH TO KHACHHANG;

--12/ XEM DANH SÁCH TẤT CẢ NHA SĨ CHƯA BỊ KHÓA TÀI KHOẢN
GRANT EXECUTE ON SP_XEMDANHSACHNHASI_ALL TO KHACHHANG;

--13/ XEM THÔNG TIN TOÀN BỘ BẢNG CA
GRANT EXECUTE ON SP_XEMCA_ALL TO KHACHHANG;

--IV/ Phân quyền cho role QTV
--1/ THÊM LOẠI THUỐC MỚI
GRANT EXECUTE ON SP_THEMLOAITHUOC_QTV TO QTV;

--1/ THÊM LOẠI THUỐC MỚI
GRANT EXECUTE ON SP_THEMLOAITHUOC_QTV TO QTV;

--2/ HỦY THUỐC
GRANT EXECUTE ON SP_HUYTHUOC_QTV TO QTV;

--3/ CẬP NHẬT BẢNG LOẠI THUỐC
GRANT EXECUTE ON SP_CAPNHATLOAITHUOC_QTV TO QTV;

--4/ NHẬP THÊM THUỐC VÀO THUỐC ĐÃ CÓ SẴN
GRANT EXECUTE ON SP_NHAPTHEMTHUOC_QTV TO QTV;

--5/ THÊM LOẠI DỊCH VỤ MỚI
GRANT EXECUTE ON SP_THEMDICHVU_QTV TO QTV;

--6/ CẬP NHẬT BẢNG LOẠI DỊCH VỤ
GRANT EXECUTE ON SP_CAPNHATDICHVU_QTV TO QTV;

--7/ XEM DANH SÁCH NHÂN VIÊN
GRANT EXECUTE ON SP_XEMDANHSACHNHANVIEN TO QTV;

--8/ TẠO NHÂN VIÊN MỚI
GRANT EXECUTE ON SP_CREATENV_QTV TO QTV;

--9/ CẬP NHÂT THÔNG TIN NHÂN VIÊN
GRANT EXECUTE ON SP_UPDATENV_QTV TO QTV;

--10/ KHÓA TÀI KHOẢN NHÂN VIÊN
GRANT EXECUTE ON SP_BLOCKNV_QTV TO QTV;

--11/ MỞ KHÓA TK NHÂN VIÊN
GRANT EXECUTE ON SP_UNBLOCKNV_QTV TO QTV;

--12/ XEM DANH SÁCH NHA SĨ
GRANT EXECUTE ON SP_GETALLNS_QTV TO QTV;

--13/ TẠO NHA SĨ MỚI
GRANT EXECUTE ON SP_CREATENS_QTV TO QTV;

--14/ CẬP NHẬT THÔNG TIN NHA SĨ
GRANT EXECUTE ON SP_UPDATENS_QTV TO QTV;

--15/ KHÓA TÀI KHOẢN NHA SĨ
GRANT EXECUTE ON SP_KHOA_TAI_KHOAN_NHA_SI TO QTV;

--16/ MỞ KHÓA TK NHA SĨ
GRANT EXECUTE ON SP_MO_TAI_KHOAN_NHA_SI TO QTV;

--17/ XEM DANH SÁCH QTV
GRANT EXECUTE ON SP_XEM_DANH_SACH_QTV TO QTV;

--18/ TẠO QUẢN TRỊ VIÊN MỚI
GRANT EXECUTE ON SP_TAO_QTV_MOI TO QTV;

--19/ XEM DANH SÁCH KHÁCH HÀNG
GRANT EXECUTE ON SP_XEM_DANH_SACH_KHACH_HANG TO QTV;

--20/ KHÓA TÀI KHOẢN KHÁCH HÀNG
GRANT EXECUTE ON SP_KHOA_TAI_KHOAN_KHACH_HANG TO QTV;

--21/ MỞ KHÓA TK KHÁCH HÀNG
GRANT EXECUTE ON SP_MO_TAI_KHOAN_KHACH_HANG TO QTV;

--22/ ĐỔI MẬT KHẨU QTV
GRANT EXECUTE ON SP_DOIMK_NS TO QTV;

--23/ XEM DANH MỤC THUỐC
GRANT EXECUTE ON SP_GETALLTHUOC_NV_QTV_NS TO QTV;

--24/ XEM DANH MỤC DỊCH VỤ
GRANT EXECUTE ON SP_XEMDANHSACHDICHVU_ALL TO QTV;

--25/ XEM DANH SÁCH TẤT CẢ NHA SĨ CHƯA BỊ KHÓA TÀI KHOẢN
GRANT EXECUTE ON SP_XEMDANHSACHNHASI_ALL TO QTV;

--26/ XEM THÔNG TIN TOÀN BỘ BẢNG CA
GRANT EXECUTE ON SP_XEMCA_ALL TO QTV;


--V/ Phân quyền cho role KHACHHANGONLINE

--1/ ĐĂNG NHẬP
GRANT EXECUTE ON SP_DANGNHAP_ALL TO KHACHHANGONLINE;

--2/ XEM DANH SÁCH TẤT CẢ NHA SĨ CHƯA BỊ KHÓA TÀI KHOẢN
GRANT EXECUTE ON SP_XEMDANHSACHNHASI_ALL TO KHACHHANGONLINE;

--3/ XEM DANH MỤC DỊCH VỤ
GRANT EXECUTE ON SP_XEMDANHSACHDICHVU_ALL TO KHACHHANGONLINE;

--4/ TẠO TÀI KHOẢN 
GRANT EXECUTE ON SP_TAOTKKH_KH TO KHACHHANGONLINE;
