USE PKNHAKHOA
GO
--------------
--1/ Tạo tài khoản Khách Hàng (KH, NV)
CREATE OR ALTER PROC SP_TAOTKKH_NV_KH
	@SODT VARCHAR(100),
	@HOTEN NVARCHAR(50),
	@PHAI NVARCHAR(5),
	@NGAYSINH DATE,
	@DIACHI NVARCHAR(250),
	@MATKHAU VARCHAR(20)
AS
BEGIN TRAN
	BEGIN TRY
		IF EXISTS(SELECT 1 FROM KHACHHANG WHERE SODT = @SODT)
			OR EXISTS(SELECT 1 FROM QTV WHERE MAQTV = @SODT)
			OR EXISTS(SELECT 1 FROM NHANVIEN WHERE MANV = @SODT)
			OR EXISTS(SELECT 1 FROM NHASI WHERE MANS = @SODT)
		BEGIN
			RAISERROR(N'Tài khoản đã tồn tại trong hệ thống', 16, 1);
			ROLLBACK TRAN
			RETURN
		END
		ELSE
		BEGIN
			INSERT INTO KHACHHANG(SODT, HOTEN, PHAI, NGAYSINH, DIACHI, MATKHAU) 
			VALUES(@SODT, @HOTEN, @PHAI, @NGAYSINH, @DIACHI, @MATKHAU)
		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN;
		DECLARE @errorMessage NVARCHAR(200) = ERROR_MESSAGE();
		THROW 51000, @errorMessage, 1;
		RETURN
	END CATCH
COMMIT TRAN

-------------------------------------------------------
--4/ Tạo lịch hẹn khám (KH, NV)
GO
CREATE OR ALTER PROC SP_DATLICHHEN_NV_KH
	@SODT VARCHAR(100),
	@MANS VARCHAR(100),
	@SOTT INT,
	@LYDOKHAM VARCHAR(200)
AS
BEGIN TRAN
	BEGIN TRY
		BEGIN
			INSERT INTO LICHHEN(MANS, SODT, LYDOKHAM, SOTT) 
			VALUES(@MANS, @SODT, @LYDOKHAM, @SOTT)
		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN;
		DECLARE @errorMessage NVARCHAR(200) = ERROR_MESSAGE();
		THROW 51000, @errorMessage, 1;
		RETURN
	END CATCH
COMMIT TRAN
---------------------------
--5/ Tạo hóa đơn (NV)
GO
CREATE OR ALTER PROC SP_TAOHOADON_NV
	@SODT VARCHAR(100),
	@SOTT INT,
	@MANV VARCHAR(100)
AS
BEGIN TRAN
	BEGIN TRY
		IF EXISTS(SELECT 1 FROM HOSOBENH WHERE SODT = @SODT AND SOTT = @SODT AND _DAXUATHOADON = 1)
		BEGIN
			RAISERROR(N'Hồ sơ bệnh đã được xuất hóa đơn', 16, 1);
			ROLLBACK TRAN
			RETURN
		END

		IF NOT EXISTS(SELECT 1 FROM CHITIETDV WHERE SODT = @SODT AND SOTT = @SOTT)
		BEGIN
			RAISERROR(N'Hồ sơ bệnh chưa được thêm dịch vụ vào', 16, 1);
			ROLLBACK TRAN
			RETURN
		END
		ELSE

		BEGIN
			DECLARE @TONGCHIPHI FLOAT;
			DECLARE @TIENDV FLOAT
			DECLARE @TIENTHUOC FLOAT;

			SELECT @TIENTHUOC = ISNULL(SUM(DONGIA * SOLUONG), 0)
			FROM CHITIETTHUOC CTT
			LEFT JOIN LOAITHUOC LT ON CTT.MATHUOC = LT.MATHUOC
			WHERE CTT.SODT = @SODT AND CTT.SOTT = @SOTT;

			SELECT @TIENDV = ISNULL(SUM(DONGIA * SOLUONG), 0)
			FROM CHITIETDV CTDV
			LEFT JOIN LOAIDICHVU LDV ON LDV.MADV = CTDV.MADV
			WHERE CTDV.SODT = @SODT AND CTDV.SOTT = @SOTT;
			
			SET @TONGCHIPHI = @TIENTHUOC + @TIENDV

			INSERT INTO HOADON(SODT, SOTT, NGAYXUAT, TONGCHIPHI, _DATHANHTOAN, MANV)
			VALUES(@SODT, @SOTT, GETDATE(), @TONGCHIPHI, 0, @MANV)

			UPDATE HOSOBENH 
			SET _DAXUATHOADON = 1
			WHERE SOTT = @SOTT AND SODT = @SODT

		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN;
		DECLARE @errorMessage NVARCHAR(200) = ERROR_MESSAGE();
		THROW 51000, @errorMessage, 1;
		RETURN
	END CATCH
COMMIT TRAN
-------------------------------------------
--6/ Truy vấn hóa đơn của 1 KH(NV, KH)
GO
CREATE OR ALTER PROC SP_GETHOADON1KH_NV
	@SODT VARCHAR(100)
AS
BEGIN TRAN
	BEGIN TRY
		IF (NOT EXISTS(SELECT * FROM KHACHHANG WHERE SODT = @SODT))
		BEGIN
			RAISERROR(N'Tài khoản này không tồn tại', 16, 1);
			ROLLBACK TRAN
			RETURN
		END
		
		IF (NOT EXISTS(SELECT * FROM HOADON WHERE SODT = @SODT))
		BEGIN
			RAISERROR(N'Tài khoản không có hóa đơn nào', 16, 1);
			ROLLBACK TRAN
			RETURN
		END

		ELSE
		BEGIN
			SELECT KH.HOTEN, HD.SODT SODT, NGAYXUAT, TONGCHIPHI, NV.HOTEN NVXUATHD,
			(
				SELECT TENDV, SOLUONG, DONGIA
				FROM CHITIETDV CTDV 
				JOIN LOAIDICHVU LDV ON CTDV.MADV = LDV.MADV
				WHERE HD.SODT = CTDV.SODT AND CTDV.SOTT = HD.SOTT
				FOR JSON PATH
			) AS DICHVU_ARR,
			(
				SELECT TENTHUOC, SOLUONG, DONGIA
				FROM CHITIETTHUOC CTT 
				JOIN LOAITHUOC LT ON CTT.MATHUOC = LT.MATHUOC
				WHERE HD.SODT = CTT.SODT AND CTT.SOTT = HD.SOTT
				FOR JSON PATH
			) AS THUOC_ARR
			FROM HOADON HD
			JOIN KHACHHANG KH ON HD.SODT = KH.SODT
			JOIN NHANVIEN NV ON NV.MANV = HD.MANV
			WHERE HD.SODT = @SODT
			FOR JSON PATH;
		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN;
		DECLARE @errorMessage NVARCHAR(200) = ERROR_MESSAGE();
		THROW 51000, @errorMessage, 1;
		RETURN
	END CATCH
COMMIT TRAN
----------------------------------
--10/ Trả về tất cả loại thuốc (NV, QTV)
GO
CREATE OR ALTER PROC SP_GETALLTHUOC_NV
AS
BEGIN TRAN
	BEGIN TRY
		SELECT * FROM LOAITHUOC
		FOR JSON PATH;
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN;
		DECLARE @errorMessage NVARCHAR(200) = ERROR_MESSAGE();
		THROW 51000, @errorMessage, 1;
		RETURN
	END CATCH
COMMIT TRAN
-------------------------------------
--23/ Truy vấn lịch hẹn của 1 nha sĩ (NS, NV)
GO
CREATE OR ALTER PROC SP_GETLICHRANH1NS_KH_NV_NS
	@MANS VARCHAR(100)
AS
BEGIN TRAN
	BEGIN TRY
		IF (NOT EXISTS(SELECT * FROM NHASI WHERE MANS = @MANS))
		BEGIN
			RAISERROR(N'Nha sĩ này không tồn tại', 16, 1);
			ROLLBACK TRAN
			RETURN
		END
		
		ELSE
		BEGIN
			SELECT KH.HOTEN HOTENKH, KH.SODT SODT, LYDOKHAM, NS.MANS, NS.HOTEN 
			FROM LICHHEN LH
			JOIN NHASI NS ON LH.MANS = NS.MANS
			JOIN KHACHHANG KH ON KH.SODT = LH.SODT
			WHERE LH.MANS = @MANS
			FOR JSON PATH;
		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN;
		DECLARE @errorMessage NVARCHAR(200) = ERROR_MESSAGE();
		THROW 51000, @errorMessage, 1;
		RETURN
	END CATCH
COMMIT TRAN
---------------
--Thanh toán hóa đơn
GO
CREATE OR ALTER PROC SP_THANHTOANHOADON_KH_NV
	@SODT VARCHAR(100),
	@SOTT INT
AS
BEGIN TRAN
	BEGIN TRY
		IF (NOT EXISTS(SELECT * FROM HOADON WHERE SODT = @SODT AND SOTT = @SOTT))
		BEGIN
			RAISERROR(N'Hoá đơn này không tồn tại', 16, 1);
			ROLLBACK TRAN
			RETURN
		END

		IF (EXISTS(SELECT * FROM HOADON WHERE SODT = @SODT AND SOTT = @SOTT AND _DATHANHTOAN = 1))
		BEGIN
			RAISERROR(N'Hoá đơn này đã được thanh toán', 16, 1);
			ROLLBACK TRAN
			RETURN
		END
		
		ELSE
		BEGIN
			UPDATE HOADON
			SET	_DATHANHTOAN = 1
			WHERE SODT = @SODT AND SOTT = @SOTT
		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN;
		DECLARE @errorMessage NVARCHAR(200) = ERROR_MESSAGE();
		THROW 51000, @errorMessage, 1;
		RETURN
	END CATCH
COMMIT TRAN
---------------------
--Truy vấn hồ sơ bệnh án của 1 KH
GO
CREATE OR ALTER PROC SP_GETHSB1KH_NV_NS_KH
	@SODT VARCHAR(100)
AS
BEGIN TRAN
	BEGIN TRY
		IF (NOT EXISTS(SELECT * FROM KHACHHANG WHERE SODT = @SODT))
		BEGIN
			RAISERROR(N'Khách hàng này không tồn tại', 16, 1);
			ROLLBACK TRAN
			RETURN
		END
		
		ELSE
		BEGIN
			SELECT SOTT,HSB.SODT SODT, KH.HOTEN HOTEN, DATEDIFF(year,KH.NGAYSINH,GETDATE()) TUOI, NGAYKHAM, NS.HOTEN NHASI, DANDO,
					(SELECT TENDV, SOLUONG
						FROM CHITIETDV CTDV JOIN LOAIDICHVU LDV
						ON CTDV.MADV =  LDV.MADV
						WHERE CTDV.SODT = HSB.SODT
						FOR JSON PATH
					) AS DICHVU_ARR,
					(SELECT TENTHUOC, SOLUONG, DONVITINH
						FROM CHITIETTHUOC CTT JOIN LOAITHUOC LT
						ON CTT.MATHUOC =  LT.MATHUOC
						WHERE CTT.SODT = HSB.SODT
						FOR JSON PATH
					) AS THUOC_ARR
			FROM HOSOBENH HSB 
			JOIN NHASI NS ON HSB.MANS = NS.MANS
			JOIN KHACHHANG KH ON KH.SODT = HSB.SODT
			WHERE HSB.SODT = @SODT
			FOR JSON PATH;
		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN;
		DECLARE @errorMessage NVARCHAR(200) = ERROR_MESSAGE();
		THROW 51000, @errorMessage, 1;
		RETURN
	END CATCH
COMMIT TRAN
--------------------------
--Lấy lịch trực của các nha sĩ từ giờ đến 7 ngày kế
GO
CREATE OR ALTER PROC SP_GETLICHRANHNS_NV_KH_NS
AS
BEGIN TRAN
	BEGIN TRY
		SELECT LR.MANS MANS, HOTEN, 
		(
			SELECT SOTT, GIOBATDAU, GIOKETTHUC, NGAY
			FROM LICHRANH LR2
			JOIN CA ON LR2.MACA = CA.MACA
			WHERE LR2.MANS = LR.MANS
			AND DATEDIFF(DAY,GETDATE(),NGAY) <= 7
			FOR JSON PATH
		) AS THOIGIANRANH_ARR
		FROM LICHRANH LR
		JOIN NHASI NS ON LR.MANS = NS.MANS
		FOR JSON PATH
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN;
		DECLARE @errorMessage NVARCHAR(200) = ERROR_MESSAGE();
		THROW 51000, @errorMessage, 1;
		RETURN
	END CATCH
COMMIT TRAN
---------------------

